export const REGISTER_SUCCESS_MESSAGE = 'REGISTER_SUCCESS_MESSAGE';
export const REGISTER_ERROR_MESSAGE = 'REGISTER_ERROR_MESSAGE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';