export const REGISTER_SUCCESS_MESSAGE = 'REGISTER_SUCCESS_MESSAGE';
export const REGISTER_ERROR_MESSAGE = 'REGISTER_ERROR_MESSAGE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const GET_ALL_USER_PLAYERS = 'GET_ALL_USER_PLAYERS';

export const GET_PLAYER_BY_ID = 'GET_PLAYER_BY_ID';

export const ERROR_GET_PLAYER = 'ERROR_GET_PLAYER';


//searchReducer

export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const ERROR_SEARCH = 'ERROR_SEARCH';

