export const REGISTER_SUCCESS_MESSAGE = 'REGISTER_SUCCESS_MESSAGE';
export const REGISTER_ERROR_MESSAGE = 'REGISTER_ERROR_MESSAGE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';

export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const GET_PLAYER_BY_ID = 'GET_PLAYER_BY_ID';
export const GET_ALL_USER_PLAYERS = 'GET_ALL_USER_PLAYERS';
export const ERROR_CREATE_PLAYER = 'ERROR_CREATE_PLAYER';